const familyRootTypes = {
  SET_FAMILY_NAME: 'SET_FAMILY_NAME',
  SET_BOY_NAME: 'SET_BOY_NAME',
  SET_PRIMARY_ATTRIBUTE: 'SET_PRIMARY_ATTRIBUTE',
  SET_STARTER_PET: 'SET_STARTER_PET',
  SET_PET_NAME: 'SET_PET_NAME'
}

export default familyRootTypes;