const familyRootTypes = {
  SET_FAMILY_NAME: 'SET_FAMILY_NAME',
  SET_PRIMARY_ATTRIBUTE: 'SET_PRIMARY_ATTRIBUTE',
  ADD_NEW_CHARACTER: 'ADD_NEW_CHARACTER',
  SET_STARTER_PET: 'SET_STARTER_PET',
  SET_PET_NAME: 'SET_PET_NAME',
  SET_PET_TYPE: 'SET_PET_TYPE',
  SET_CHARACTER_PROPERTY: 'SET_CHARACTER_PROPERTY'
}

export default familyRootTypes;