export const SET_CURRENT_CHARACTER = 'SET_CURRENT_CHARACTER';
export const START_GAME_TIMER = 'START_GAME_TIMER';
export const INCREMENT_GAME_MONTH = 'INCREMENT_GAME_MONTH';
export const SET_CURRENT_PAGE = 'SET_CURRENT_PAGE';
export const SET_CURRENT_VIEW = 'SET_CURRENT_VIEW';
export const SET_CURRENT_CHARACTER_FOR_DETAIL_VIEW = 'SET_CURRENT_CHARACTER_FOR_DETAIL_VIEW'
export const SET_MAP_POSITION = 'SET_MAP_POSITION';
export const VIEW_CHARACTER_ON_MAP = 'VIEW_CHARACTER_ON_MAP';



export const DEV_ONLY_SET_GAME_SEEDED_INFO = 'DEV_ONLY_SET_GAME_SEEDED_INFO';