export const SET_CURRENT_CHARACTER = 'SET_CURRENT_CHARACTER';
export const START_GAME_TIMER = 'START_GAME_TIMER';
export const INCREMENT_GAME_MONTH = 'INCREMENT_GAME_MONTH';
export const SET_CURRENT_PAGE = 'SET_CURRENT_PAGE';
export const SET_LAST_MAP_POSITION = 'SET_LAST_MAP_POSITION';