export const SET_CURRENT_CHARACTER = 'SET_CURRENT_CHARACTER';
export const START_GAME_TIMER = 'START_GAME_TIMER';
export const INCREMENT_GAME_MONTH = 'INCREMENT_GAME_MONTH';
export const SET_CURRENT_PAGE = 'SET_CURRENT_PAGE';
export const SET_CURRENT_VIEW = 'SET_CURRENT_VIEW';
export const SET_CURRENT_CHARACTER_FOR_DETAIL_VIEW = 'SET_CURRENT_CHARACTER_FOR_DETAIL_VIEW'



export const DEV_ONLY_SET_GAME_SEEDED_INFO = 'DEV_ONLY_SET_GAME_SEEDED_INFO';